---
- name: Create and Configure website and app pool
  hosts: all

  tasks:
    - name: Create a new application pool in Started state
      win_iis_webapppool:
        name: ansibledemo
        state: started
        attributes: 'managedRuntimeVersion:v4.0'
      register: webapppool

    - name: Create directory structure for new website
      win_file:
        path: c:\inetpub\wwwroot\ansibledemo
        state: directory
        
    - name: Create ansibledemo website
      win_iis_website:
        name: "ansibledemo"
        state: started
        port: 8081
        ip: 127.0.0.1
        application_pool: "ansibledemo"
        physical_path: c:\inetpub\wwwroot\ansibledemo
      register: website
      
    - name: Download the source from the repository
      win_get_url:
        url: 'https://github.com/vijeyashokk/ansibleiisconfig/blob/master/source/default.html'
        dest: 'C:\windows\temp\default.html'

    - name: Recursively decompress the files into the directory
      win_copy:
        src: 'C:\windows\temp\default.html'
        dest: 'c:\inetpub\wwwroot\ansibledemo\default.html'



